#config_version=6

mode:
  start_events: ball_started
  stop_events:
    - skill_success
    - skill_failed
  priority: 500

shots:
  skill_1:
    switch: s_right_ramp1
    profile: skill_shot_profile
    show_tokens:
      light: l_right_ramp1a
  skill_2:
    switch: s_right_ramp2
    profile: skill_shot_profile
    show_tokens:
      light: l_right_ramp2a
  skill_3:
    switch: s_left_ramp1
    profile: skill_shot_profile
    show_tokens:
      light: l_left_ramp1a
  skill_4:
    switch: s_left_ramp2
    profile: skill_shot_profile
    show_tokens:
      light: l_left_ramp2a

shot_groups:
  skill_shot:
    shots: skill_1, skill_2, skill_3, skill_4

shot_profiles:
  skill_shot_profile:
    states:
     - name: unlit
       show: off
     - name: flashing
       show: flash_color
       show_tokens:
         color: red
       speed: 4
     - name: lit
       show: on
    loop: true

variable_player:
  skill_success:
    score: 10000

timers:
  skill_shot_timeout:
    start_value: 0
    end_value: 20
    start_running: false
    control_events:
      - action: start
        event: ball_device_plunger_lane_ball_eject_success

state_machines:
  skill_shot_success:
    debug: true
    states:
      start:
        label: skill_start_ready
      success:
        label: skill successful
        events_when_started: skill_success
      failed:
        label: skill failed
        events_when_started: skill_failed
    transitions:
      - source: start
        target: success
        events: skill_shot_flashing_hit
      - source: start
        target: failed
        events: skill_shot_unlit_hit, timer_skill_shot_timeout_complete