#config_version=6

# Base mode that starts at the beginning of each ball
# and stops at the end of each ball.

mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 100

variable_player:
  mode_base_started:
  base_start_global:
    action: add_machine
    int: 1 

slide_player:
  mode_base_started: base

shots:
  my_first_shot:
    switch: s_plunger
  show_tokens:
    light: l_plunger_lane
    profile: my_first_profile

shot_profiles:
  my_first_profile:
    states:
      - name: unlit  # step 1
        show: off
      - name: flashing  # step 2
        show: flash
      - name: lit  # step 3
        show: on
    loop: true