#config_version=6

switches:
  # bouton façade flipper
  s_flipper_left: # flipper gauche
    number: 1-0-32
    tags: left_flipper
  s_flipper_right: # flipper droit
    number: 1-0-33
    tags: right_flipper
  s_plunger:  # lanceur
    number: 1-0-34
    tags: plunger
  s_start_button: # démarrer
    number: 1-0-35
    tags: start
  # magasin de billes
  s_trough1: # présence bille 1
    number: 1-0-36
  s_trough2: # mprésence bille 2
    number: 1-0-37
  s_trough3: # mprésence bille 3
    number: 1-0-38
  s_trough4: # présence bille 4
    number: 1-0-39
  s_plunger_lane: # présence bille couloir lanceur
    number: 1-0-40
  s_left_slingshot: # slingshot gauche
    number: 1-0-41
  s_right_slingshot: # slingshot droit
    number: 1-0-42
  s_left_bumper: # bumper gauche
    number: 1-0-43
  s_down_bumper: # bumper bas
    number: 1-0-44
  s_high_bumper: # bumper haut
    number: 1-0-45
  s_catapult: # éjection voie de gauche
    number: 1-0-46
  s_left_outlane: # sortie bas gauche
    number: 1-0-47
  s_left_inlane: # vers flipper gauche
    number: 1-0-48
  s_right_outlane: # sortie bas gauche
    number: 1-0-49
  s_right_inlane: # vers flipper gauche
    number: 1-0-50
  s_right_ramp1: # rampe bas droite
    number: 1-0-51
  s_right_ramp2: # rampe haut droite
    number: 1-0-52
  s_left_ramp1: # rampe haut gauche
    number: 1-0-53
  s_left_ramp2: # rampe haut gauche
    number: 1-0-54
  s_central_ramp_target: # cible rampe centrale
    number: 1-0-55
  s_left_highline: # passage haut gauche
    number: 1-0-56
  s_right_highline: # passage haut droit
    number: 1-0-57
  s_left_door: # portillon haut gauche
    number: 1-0-58
  s_right_door: # portillon haut droit
    number: 1-0-59
  s_catapult_spinner: # spinner voie gauche
    number: 1-0-60
  s_hidden_target: # cible cachée à droite sous rampe spirale
    number: 1-0-61
  s_left_target1: # cible bas gauche haut
    number: 1-0-62
  s_left_target2: # cible bas gauche bas
    number: 1-0-63
  s_right_target1: # cible bas droite haut
    number: 1-0-64
  s_right_target2: # cible bas droite bas
    number: 1-0-65
  s_left_high_target: # cible haut gauche
    number: 1-0-66
  s_right_high_target: # cible haut droit
    number: 1-0-67
  s_middle_target1: # petite cible milieu gauche
    number: 1-0-68
  s_middle_target2: # petite cible milieu droit
    number: 1-0-69
  s_central_target1: # cible centrale 1
    number: 1-0-70
  s_central_target2: # cible centrale 2
    number: 1-0-71
  s_central_target3: # cible centrale 3
    number: 1-0-72
  s_central_target4: # cible centrale 4
    number: 1-0-73
  s_falling_target: # cible tombante
    number: 1-0-74
  s_cave: # présence bille cave
    number: 1-0-75