#config_version=6

mode:
  start_events: ball_starting
  priority: 200

shots:
  vega_saucers:
     switch: s_left_bumper, s_down_bumper, s_high_bumper

counters:
  lb_caps_count:
    count_events: vega_saucers_hit
    starting_count: 0
    count_complete_value: 100
    count_interval: 1
    direction: up
    persist_state: true
    events_when_complete: Svega_saucers_Go
    debug: true
  lb_caps_resume:
    enable_events: mode_base_started{current_player.sj_active>0}
    count_events: vega_saucers_hit
    starting_count: 0
    count_complete_value: 25
    count_interval: 1
    direction: up
    persist_state: false
    events_when_complete: Svega_saucers_Resume_Go
    debug: true
    reset_on_complete: true
  lb_rollover_complete_count:
    count_events: lanes_complete
    events_when_hit: lanes_done
    starting_count: 0
    count_complete_value: 40
    reset_on_complete: false
    direction: up
    persist_state: false

event_player:
  Super_Caps_Go:
    start_mode_vega_saucers
  Super_Caps_Go_Again:
    start_mode_vega_saucers

variable_player:
  s_right_bumper_active:
    score: 10000 + (device.counters.lb_lanes_complete_count.value * 5000)
  s_down_bumper_active:
    score: 10000 + (device.counters.lb_lanes_complete_count.value * 5000)
  s_down_bumper_active:
    score: 10000 + (device.counters.lb_lanes_complete_count.value * 5000)
  lanes_complete:
    score: 20000
  mode_vega_saucers_started:
    sc_active:
      int: 1
      action: set

show_player:
  mode_vega_saucers_setup_started{current_player.sj_active>0}:
    vega_saucers_on:
      show_tokens:
        lights: l_vega_saucers